`make js` to build with js_of_ocaml and run with node; missing runtime.ml_z_init
/Users/voglerr/goblint/analyzer/_build/default/src/goblint.bc.js:24484
    runtime.ml_z_init(0);
            ^

TypeError: runtime.ml_z_init is not a function
    at /Users/voglerr/goblint/analyzer/_build/default/src/goblint.bc.js:24484:13
    at Object.<anonymous> (/Users/voglerr/goblint/analyzer/_build/default/src/goblint.bc.js:25259:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
make: *** [js] Error 1